const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder,ModalBuilder,TextInputBuilder,TextInputStyle}=require('discord.js');const emojis=require('../config/emojis.json');const DARK=0x2b2d31,ACCENT=0x5865f2;
function emoji(k){const m=(emojis[k]||'').match(/<a?:[^:]+:(\d+)>/);return m?{id:m[1]}:undefined;}
function hubEmbed(){return new EmbedBuilder().setColor(DARK).setTitle('Support Center').setDescription('Select a support category below to open a private ticket.').setFooter({text:'Pauze Tickets'});}
function ticketEmbed(t,cat){return new EmbedBuilder().setColor(DARK).setTitle(`Ticket #${String(t.id).padStart(4,'0')}`).setDescription('Your request has been created. A member of the support team will assist you shortly.').addFields({name:'Creator',value:`<@${t.userId}>`,inline:true},{name:'Category',value:cat.label,inline:true},{name:'Opened',value:`<t:${Math.floor(new Date(t.createdAt).getTime()/1000)}:R>`,inline:true},{name:'Topic',value:t.answers.topic||'Not provided'},{name:'Description',value:(t.answers.description||'Not provided').slice(0,1024)},{name:'Identifier',value:t.answers.identifier||'Not provided',inline:true});}
function panelRow(categories){return new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('ticket:category').setPlaceholder('Select a support category').addOptions(categories.map(c=>({label:c.label,value:c.value,description:c.description,emoji:emoji(c.emoji)}))));}
function controlRow(id){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`ticket:claim:${id}`).setLabel('Claim').setStyle(ButtonStyle.Secondary).setEmoji(emoji('claim')),new ButtonBuilder().setCustomId(`ticket:transcript:${id}`).setLabel('Export').setStyle(ButtonStyle.Secondary).setEmoji(emoji('transcript')),new ButtonBuilder().setCustomId(`ticket:close:${id}`).setLabel('Close').setStyle(ButtonStyle.Secondary).setEmoji(emoji('close')));}
function closeConfirm(id){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`ticket:closeconfirm:${id}`).setLabel('Confirm').setStyle(ButtonStyle.Danger).setEmoji(emoji('confirm')),new ButtonBuilder().setCustomId(`ticket:closecancel:${id}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary).setEmoji(emoji('cancel')));}
function csatRow(id){return new ActionRowBuilder().addComponents([1,2,3,4,5].map(n=>new ButtonBuilder().setCustomId(`ticket:csat:${id}:${n}`).setLabel(String(n)).setStyle(ButtonStyle.Secondary).setEmoji(emoji('star'))));}
function intakeModal(category){return new ModalBuilder().setCustomId(`ticket:intake:${category}`).setTitle('Ticket Request').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('topic').setLabel('Short Topic').setStyle(TextInputStyle.Short).setMaxLength(100).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('description').setLabel('Detailed Description').setStyle(TextInputStyle.Paragraph).setMaxLength(4000).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('identifier').setLabel('ID, Gamertag or Email (optional)').setStyle(TextInputStyle.Short).setMaxLength(200).setRequired(false)));}
function closeModal(id){return new ModalBuilder().setCustomId(`ticket:closemodal:${id}`).setTitle('Close Ticket').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('reason').setLabel('Closure Reason').setStyle(TextInputStyle.Paragraph).setMaxLength(1000).setRequired(true)));}
module.exports={DARK,ACCENT,emoji,hubEmbed,ticketEmbed,panelRow,controlRow,closeConfirm,csatRow,intakeModal,closeModal};
