const { ActionRowBuilder, ButtonBuilder, ButtonStyle, StringSelectMenuBuilder, ModalBuilder, TextInputBuilder, TextInputStyle } = require('discord.js');
const e = require('../config/emojis.json'); const emoji = key => e[key] || undefined;
function panelRow(categories){return new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('ticket:category').setPlaceholder('Select a support category').addOptions(categories.map(c=>({label:c.label,value:c.value,description:c.description,emoji:emoji(c.emoji)}))));}
function controls(id){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`ticket:claim:${id}`).setLabel('Claim').setStyle(ButtonStyle.Secondary).setEmoji(emoji('claim')),new ButtonBuilder().setCustomId(`ticket:close:${id}`).setLabel('Close').setStyle(ButtonStyle.Secondary).setEmoji(emoji('close')),new ButtonBuilder().setCustomId(`ticket:transcript:${id}`).setLabel('Export').setStyle(ButtonStyle.Secondary).setEmoji(emoji('transcript')));}
function closeConfirm(id){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`ticket:closeconfirm:${id}`).setLabel('Confirm').setStyle(ButtonStyle.Danger).setEmoji(emoji('confirm')),new ButtonBuilder().setCustomId(`ticket:closecancel:${id}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary).setEmoji(emoji('cancel')));}
function csatRow(id){return new ActionRowBuilder().addComponents(...[1,2,3,4,5].map(n=>new ButtonBuilder().setCustomId(`ticket:csat:${id}:${n}`).setLabel(String(n)).setStyle(ButtonStyle.Secondary).setEmoji(emoji('star'))));}
function intakeModal(category){return new ModalBuilder().setCustomId(`ticket:intake:${category}`).setTitle(`${category[0].toUpperCase()+category.slice(1)} Support`).addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('topic').setLabel('Short Topic').setStyle(TextInputStyle.Short).setMaxLength(100).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('description').setLabel('Detailed Description').setStyle(TextInputStyle.Paragraph).setMaxLength(2000).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('identifier').setLabel('ID / Gamertag / Email (optional)').setStyle(TextInputStyle.Short).setMaxLength(150).setRequired(false)));}
function closeModal(id){return new ModalBuilder().setCustomId(`ticket:closemodal:${id}`).setTitle('Close Ticket').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('reason').setLabel('Closure reason').setStyle(TextInputStyle.Paragraph).setMaxLength(500).setRequired(true)));}
module.exports={panelRow,controls,closeConfirm,csatRow,intakeModal,closeModal};
