const { EmbedBuilder } = require('discord.js');
const emojis = require('../config/emojis.json');
const config = require('../config/config.json');
const icon = key => emojis[key] || '';
const color = hex => Number.parseInt(String(hex || config.theme?.accent || '#5865F2').replace('#', ''), 16);
function apply(data) { const e = new EmbedBuilder().setColor(color(data.color)); if (data.title) e.setTitle(data.title); if (data.description) e.setDescription(data.description); if (data.url) e.setURL(data.url); if (data.thumbnail) e.setThumbnail(data.thumbnail); if (data.image) e.setImage(data.image); if (data.author?.name) e.setAuthor({ name: data.author.name, iconURL: data.author.iconURL || undefined, url: data.author.url || undefined }); if (data.footer) e.setFooter({ text: data.footer, iconURL: data.footerIcon || undefined }); if (data.timestamp !== false) e.setTimestamp(); return e; }
function hubEmbed() { return apply(config.embeds?.panel || { color: '#2B2D31', title: 'Support Center', description: 'Select a category below to open a private support ticket.', footer: 'Pauze Tickets' }); }
function buildTicketEmbed(ticket) { const base = config.embeds?.ticket || {}; const e = apply({ ...base, title: (base.title || 'Ticket #{id}').replace('{id}', String(ticket.id).padStart(4, '0')) }); e.addFields({ name: 'Creator', value: `<@${ticket.userId}>`, inline: true }, { name: 'Category', value: ticket.categoryName, inline: true }, { name: 'Opened', value: `<t:${Math.floor(new Date(ticket.createdAt).getTime()/1000)}:R>`, inline: true }); for (const [key, value] of Object.entries(ticket.answers || {})) if (value) e.addFields({ name: key[0].toUpperCase() + key.slice(1), value: String(value).slice(0, 1024) }); if (ticket.claimedBy) e.addFields({ name: 'Claimed by', value: `<@${ticket.claimedBy}>`, inline: true }); return e; }
module.exports = { hubEmbed, buildTicketEmbed, apply, color, icon };
