function esc(value = '') { return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
async function createTranscript(channel, ticket) {
  let before; const messages = [];
  while (true) { const batch = await channel.messages.fetch({ limit: 100, before }); if (!batch.size) break; messages.push(...batch.values()); if (batch.size < 100 || messages.length >= 5000) break; before = batch.last().id; }
  messages.sort((a, b) => a.createdTimestamp - b.createdTimestamp);
  const rows = messages.map(m => { const avatar = m.author.displayAvatarURL({ extension: 'png', size: 64 }); const text = esc(m.content || 'No text content').replace(/\n/g, '<br>'); const files = [...m.attachments.values()].map(a => `<div class="attachment"><a href="${esc(a.url)}">${esc(a.name || 'attachment')}</a></div>`).join(''); return `<article><img src="${esc(avatar)}"><section><div class="meta"><strong>${esc(m.author.username)}</strong><time>${new Date(m.createdTimestamp).toLocaleString()}</time></div><div class="content">${text}</div>${files}</section></article>`; }).join('');
  const number = String(ticket.id).padStart(4, '0');
  const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Ticket #${number} Transcript</title><style>body{margin:0;background:#313338;color:#dbdee1;font:14px system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.head{background:#2b2d31;padding:24px;border-bottom:1px solid #1e1f22}.head h1{margin:0 0 8px}.head small{color:#949ba4}main{max-width:1050px;margin:auto;padding:20px}article{display:flex;gap:12px;padding:12px 0}article img{width:40px;height:40px;border-radius:50%}section{min-width:0;flex:1}.meta{display:flex;gap:10px;align-items:baseline}.meta time{font-size:11px;color:#949ba4}.content{margin-top:3px;white-space:normal;overflow-wrap:anywhere}.attachment{margin-top:7px}.attachment a{color:#00a8fc;text-decoration:none}.attachment a:hover{text-decoration:underline}</style></head><body><header class="head"><h1>Ticket #${number}</h1><small>Creator: ${esc(ticket.userId)} · Category: ${esc(ticket.categoryName)} · Opened: ${esc(ticket.createdAt)}</small></header><main>${rows || '<p>No messages recorded.</p>'}</main></body></html>`;
  return { html, filename: `ticket-${number}.html` };
}
module.exports = { createTranscript };
